### ISSUE TITLE
👀 swiperJS 관심 있는 이슈 (6/20-6/26)

### ISSUE THREAD

**Issue by ghtea** [frontendcommitDay/tutorial_swipeJS#4]
- swiperJS issue 3개씩 체크하기

**Comment by hi-jade88** [comment]
[#5797](https://github.com/nolimits4web/swiper/issues/5797)
[#5468](https://github.com/nolimits4web/swiper/issues/5468)
[#5714](https://github.com/nolimits4web/swiper/issues/5714)

**Comment by ghtea** [comment]
- #5789 **Full screen vertical swiper - Lower page sections do not go away on scroll up**
    - https://github.com/nolimits4web/swiper/issues/5789
    - 기본동작 방식
        - 스크롤 약간만 하면 다음 슬라이드가 아래에서 위로, 이전 슬라이드보다 앞에 놓이는 동작방식
    - 이슈 설명
        - 스크롤이 다 끝나서 Swiper 밖의 다음 요소로 스크롤한 후, 다시 위로 스크롤하면 슬라이드가 z-Index 뒤에 있어서 안보임
    - 원인 추측
        - 라이브러리 결함처럼 보임, 라이브러리에서 스타일 속성 관련해서 수정해야 할수도
- #5816 **Autoheight with one image don't work**
    - https://github.com/nolimits4web/swiper/issues/5816
    - 이슈 설명
        - swiper slide 에 auto height 를 적용했지만 이미지의 크기에 맞춰서 높이 조정이 안되는 이슈
    - 원인 추측
        - 재현이 잘 안되는데, 살펴본다면 우선 이미지 스타일 속성 문제인지 아니면 좀더 특수한 이슈인지 살펴봐야 할듯
- #5623 **Swiper overflows parent #5623**
    - https://github.com/nolimits4web/swiper/issues/5623
    - 이슈 설명
        - 양옆 슬라이드가 중앙 슬라이드와 달리 cropped 되는 이슈
    - 원인 추측
        - 재현이 친절하지 않아서 프로젝트 새로 만들어서 재현 해보는 중
        - 해당 개발자의 실수일 가능성도 있음
